### ISSUE TITLE
Demo crashes - XSHOOTER

### ISSUE THREAD

**Issue by HeloiseS** [fpavogt/fcmaker#16] opened 2019-09-08 22:24 UTC
Hi,

I've been trying out the --demo and this happened with XSHOOTER so I thought I'd report it.
Cheers :)

```
>>> python -m fcmaker --demo --obid 2274416

WARNING: AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0, use the six module directly if it is still needed [astropy.extern.six]
Created TAP+ (v1.0.1) - Connection:
	Host: gea.esac.esa.int
	Use HTTPS: False
	Port: 80
	SSL Port: 443
 
2274416: fetching the OB parameters ...
2274416: creating the finding chart ...
   Downloading the DSS2 Red background image with SkyView ...
Downloading https://skyview.gsfc.nasa.gov/tempspace/fits/skv1477848105399.fits
|==========================================|  16M/ 16M (100.00%)      3m16s
   Querying GAIA DR2 to look for high proper motion stars in the area ...
   Querying UCAC2 via Vizier to look for possible Guide Stars ...
findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fste075/.local/lib/python3.6/site-packages/fcmaker/__main__.py", line 214, in <module>
    do_parang = args.do_parang,
  File "/home/fste075/.local/lib/python3.6/site-packages/fcmaker/fcmaker.py", line 255, in make_fc
    do_pdf=do_pdf, do_png=do_png)
  File "/home/fste075/.local/lib/python3.6/site-packages/fcmaker/fcmaker_plots.py", line 632, in draw_fc
    fig1.savefig(fn_out+'.jpg')
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2082, in print_figure
    **kwargs)
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 579, in print_jpg
    buf, size = self.print_to_buffer()
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 535, in print_to_buffer
    FigureCanvasAgg.draw(self)
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/fste075/.local/lib/python3.6/site-packages/astropy/visualization/wcsaxes/core.py", line 458, in draw
    super().draw(renderer, inframe=inframe)
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/fste075/.local/lib/python3.6/site-packages/astropy/visualization/wcsaxes/core.py", line 49, in draw
    self.axes.draw_wcsaxes(renderer)
  File "/home/fste075/.local/lib/python3.6/site-packages/astropy/visualization/wcsaxes/core.py", line 422, in draw_wcsaxes
    ticks_locs=ticks_locs[coord])
  File "/home/fste075/.local/lib/python3.6/site-packages/astropy/visualization/wcsaxes/coordinate_helpers.py", line 558, in _draw_ticks
    tick_out_size=self.ticks.out_size)
  File "/home/fste075/.local/lib/python3.6/site-packages/astropy/visualization/wcsaxes/ticklabels.py", line 221, in draw
    bb = super().get_window_extent(renderer)
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/text.py", line 890, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/text.py", line 298, in _get_layout
    clean_line, self._fontproperties, ismath=ismath)
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 206, in get_text_width_height_descent
    self.mathtext_parser.parse(s, self.dpi, prop)
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/mathtext.py", line 3362, in parse
    font_output = fontset_class(prop, backend)
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/mathtext.py", line 671, in __init__
    self._stix_fallback = StixFonts(*args, **kwargs)
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/mathtext.py", line 984, in __init__
    fullpath = findfont(name)
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/font_manager.py", line 1238, in findfont
    rc_params)
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/font_manager.py", line 1270, in _findfont_cached
    + self.score_size(prop.get_size(), font.size))
  File "/home/fste075/.local/lib/python3.6/site-packages/matplotlib/font_manager.py", line 1151, in score_weight
    w1 = weight1 if isinstance(weight1, Number) else weight_dict[weight1]
KeyError: '500'
```

**Comment by fpavogt** [comment] 2019-09-09 18:28
Hum ... I encountered the same error the other day with another code. I still did not manage to get to the bottom of it. It's worrying me a bit ... As a work around, could you try to run the same command with `--systemtex` ? This might fix it (but will require that you have Latex installed, which may not be the case).

**Comment by fpavogt** [comment] 2019-09-09 19:10
So, I can't reproduce the bug on my Mac, and I do not have easy access to my usual linux server to test this out right away. I don't know why this happens, but it looks like there is a bug when setting the font weight. The only place I do it in the code is in `fcmaker_plots.py` for N-E labels. 

If you want to experiment, you can try to remove the keywors ` weight='heavy',` from l.93 and l.97 in this file. This might by-pass the problem (but won't fix it).

**Comment by JohnPritchard** [comment] 2019-09-10 06:32
Hi Frederic,

I found and fixed this in the p2fc version of fcmaker by updating eso_fcmaker_plots.mplstyle and eso_fcmaker_plots_nolatex.mplstyle replacing:

-font.weight: 500
+font.weight: medium

This seems to have been introduced in matplotlib-3.1.0. The problem seems to be that matplotlib has lost the ability to interpret integer weights.

Hope this helps.
Best regards
John

--  +  --  John Pritchard
  +E S+    User Support Department
    O      Data Management and Operations Division
--  +  --  European Southern Observatory
           Karl-Schwarzschild-Str. 2, D-85748 Garching bei München
           Off: +49 89 3200 6496 Fax: +49 89 320 2362
           mailto:john.pritchard@eso.org
           http://www.eso.org/~jpritcha

**Comment by fpavogt** [comment] 2019-09-10 09:19
Hi @JohnPritchard - thanks for the pointer! 
This looks like a bad side effect associated to [v3.1.1 of matplotlib](https://matplotlib.org/3.1.1/api/api_changes.html#fontmanager-scores). I submitted a bug report about it. matplotlib/matplotlib#15240

**Comment by fpavogt** [comment] 2020-04-24 11:46
Fixed in [v105,](https://github.com/fpavogt/fcmaker/tree/v105.0.0).

**Closed by fpavogt** 2020-04-24 11:46 UTC
Labels: bug
